include(AddCXXFlagsIfSupported)

set(VPV_CXX_FLAGS " ")

if (NOT MSVC)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-pedantic"                            HAS_PEDANTIC)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wall"                                HAS_WALL)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wextra"                              HAS_WEXTRA)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wundef"                              HAS_WUNDEF)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wunreachable-code"                   HAS_WUNREACHABLE_CODE)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wwrite-strings"                      HAS_WWRITE_STRINGS)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wdisabled-optimization"              HAS_WDISABLED_OPTIMIZATION)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wformat-security"                    HAS_WFORMAT_SECURITY)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wpointer-arith"                      HAS_WPOINTER_ARITH)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wmissing-include-dirs"               HAS_WMISSING_INCLUDE_DIRS)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wredundant-decls"                    HAS_WREDUNDANT_DECLS)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wlogical-op"                         HAS_WLOGICAL_OP)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wundef"                              HAS_WUNDEF)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wextra-semi"                         HAS_WEXTRA_SEMI)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wlogical-not-parentheses"            HAS_WLOGICAL_NOT_PARENTHESES)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wswitch-bool"                        HAS_WSWITCH_BOOL)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Woverloaded-virtual"                 HAS_WOVERLOADED_VIRTUAL)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wctor-dtor-privacy"                  HAS_WCTO_DTOR_PRIVACY)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wswitch-default"                     HAS_WSWITCH_DEFAULT)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Weffc++"                             HAS_WEFFCPP)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wcast-align"                         HAS_WCAST_ALIGN)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wcast-qual"                          HAS_WCAST_QUAL)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wdouble-promotion"                   HAS_WDOUBLE_PROMOTION)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wformat=2"                           HAS_WFORMAT_2)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wformat-nonliteral"                  HAS_WFORMAT_NONLITERAL)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wmissing-declarations"               HAS_WMISSING_DECLARATIONS)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wmissing-prototypes"                 HAS_WMISSING_PROTOTYPES)
    #add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wmissing-variable-declarations"      HAS_WMISSING_VARIABLE_DECLARATIONS)

    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wno-unused"                          HAS_WNO_UNUSED)
    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wno-unused-parameter"                HAS_WNO_UNUSED_PARAMETER)

    add_cxx_flag_if_supported(VPV_CXX_FLAGS "-Wno-sign-compare"                    HAS_WNO_SIGN_COMPARE)
endif()

separate_arguments(VPV_CXX_FLAGS)
