pipeline:
  build:
    image: ubuntu:bionic
    commands:
    - apt-get update
    - apt-get install -qq build-essential wget
      # install a custom version of cmake because bionic is old
    - wget https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5-Linux-x86_64.tar.gz -O cmake.tar.gz
    - tar xf cmake.tar.gz --strip 1 -C /usr
    - apt-get install -qq libsdl2-dev libpng-dev libtiff-dev libjpeg-dev
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
    - make
    - ctest --output-on-failure
    - make install
